language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
before_script:
  - phpenv config-rm xdebug.ini
install:
  - composer install
script:
  - vendor/bin/php-cs-fixer fix --using-cache=no --config=.php_cs.dist --verbose --diff --dry-run --stop-on-violation
  - vendor/bin/phpunit
