language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
install:
  - composer install
script:
  - vendor/bin/php-cs-fixer fix --using-cache=no --config=.php_cs.dist --verbose --diff --dry-run --stop-on-violation
  - vendor/bin/phpunit
